/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Budsaba
 */
public class ben2 extends javax.swing.JFrame {

    /**
     * Creates new form ben2
     */
    public ben2() {
        initComponents();
         setSize (500,500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        b1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        b2 = new javax.swing.JTextField();
        b4 = new javax.swing.JTextField();
        b7 = new javax.swing.JTextField();
        b8 = new javax.swing.JTextField();
        b3 = new javax.swing.JTextField();
        b6 = new javax.swing.JTextField();
        b5 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        n1 = new javax.swing.JTextField();
        n4 = new javax.swing.JTextField();
        n5 = new javax.swing.JTextField();
        n6 = new javax.swing.JTextField();
        n7 = new javax.swing.JTextField();
        n2 = new javax.swing.JTextField();
        n8 = new javax.swing.JTextField();
        n3 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        องศาฟาเรนไฮต์ = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("โปรแกรมแปลงอุณภูมิ");
        getContentPane().setLayout(null);

        jLabel2.setText("องศาฟาเรนไฮต์");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 42, 72, 14);

        b1.setBackground(new java.awt.Color(0, 255, 255));
        getContentPane().add(b1);
        b1.setBounds(90, 30, 65, 30);

        jLabel4.setText("องศาเซลเซียส");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 67, 68, 14);

        jLabel5.setText("เคลวิน");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 96, 30, 22);

        jLabel6.setText("องศาโรเมอร์");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 130, 57, 22);

        jLabel7.setText("องศาเซลเซียส");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 159, 68, 22);

        jLabel8.setText("องศาเซลเซียส");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 188, 68, 22);

        jLabel9.setText("เคลวิน");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 217, 30, 22);

        b2.setBackground(new java.awt.Color(51, 255, 255));
        getContentPane().add(b2);
        b2.setBounds(90, 60, 65, 30);

        b4.setBackground(new java.awt.Color(0, 255, 255));
        getContentPane().add(b4);
        b4.setBounds(90, 120, 65, 30);

        b7.setBackground(new java.awt.Color(0, 255, 255));
        getContentPane().add(b7);
        b7.setBounds(90, 210, 65, 30);

        b8.setBackground(new java.awt.Color(0, 255, 255));
        getContentPane().add(b8);
        b8.setBounds(90, 240, 65, 30);

        b3.setBackground(new java.awt.Color(0, 255, 255));
        getContentPane().add(b3);
        b3.setBounds(90, 90, 65, 30);

        b6.setBackground(new java.awt.Color(0, 255, 255));
        getContentPane().add(b6);
        b6.setBounds(90, 180, 65, 30);

        b5.setBackground(new java.awt.Color(51, 255, 255));
        getContentPane().add(b5);
        b5.setBounds(90, 150, 65, 30);

        jLabel18.setText("องศาเซลเซียส");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(250, 50, 68, 14);

        jLabel19.setText("องศาฟาเรนไฮต์");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(250, 70, 72, 14);

        jLabel20.setText("องศาเซลเซียส");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(249, 100, 68, 14);

        jLabel21.setText("องศาเซลเซียส");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(250, 130, 68, 14);

        jLabel22.setText("องศาโมเมอร์");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(251, 163, 59, 14);

        jLabel23.setText("เคลวิน");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(251, 192, 30, 14);

        jLabel24.setText("องศาฟาเรนไฮต์");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(250, 220, 72, 14);

        jLabel25.setText("เคลวิน");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(250, 250, 30, 14);

        n1.setBackground(new java.awt.Color(255, 255, 102));
        getContentPane().add(n1);
        n1.setBounds(330, 29, 71, 30);

        n4.setBackground(new java.awt.Color(255, 255, 102));
        getContentPane().add(n4);
        n4.setBounds(331, 121, 71, 30);

        n5.setBackground(new java.awt.Color(255, 255, 102));
        getContentPane().add(n5);
        n5.setBounds(331, 150, 71, 30);

        n6.setBackground(new java.awt.Color(255, 255, 102));
        getContentPane().add(n6);
        n6.setBounds(331, 179, 71, 30);

        n7.setBackground(new java.awt.Color(255, 255, 102));
        getContentPane().add(n7);
        n7.setBounds(331, 208, 71, 30);

        n2.setBackground(new java.awt.Color(255, 255, 102));
        getContentPane().add(n2);
        n2.setBounds(331, 58, 71, 30);

        n8.setBackground(new java.awt.Color(255, 255, 102));
        getContentPane().add(n8);
        n8.setBounds(331, 242, 71, 30);

        n3.setBackground(new java.awt.Color(255, 255, 102));
        getContentPane().add(n3);
        n3.setBounds(331, 87, 71, 30);

        jLabel26.setText("องศาฟาเรนไฮต์");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(10, 255, 72, 14);

        jLabel27.setBackground(new java.awt.Color(255, 51, 51));
        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel27.setText("สูตรการแปลงอุณภูมิ");
        getContentPane().add(jLabel27);
        jLabel27.setBounds(150, 0, 193, 22);

        jButton1.setText("แปลงเป็น");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(170, 70, 77, 23);

        องศาฟาเรนไฮต์.setText("แปลงเป็น");
        องศาฟาเรนไฮต์.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                องศาฟาเรนไฮต์ActionPerformed(evt);
            }
        });
        getContentPane().add(องศาฟาเรนไฮต์);
        องศาฟาเรนไฮต์.setBounds(170, 40, 77, 23);

        jButton3.setText("แปลงเป็น");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(170, 190, 77, 23);

        jButton4.setText("แปลงเป็น");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(170, 100, 77, 23);

        jButton5.setText("แปลงเป็น");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(170, 130, 77, 23);

        jButton6.setText("แปลงเป็น");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(170, 220, 77, 23);

        jButton7.setText("แปลงเป็น");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(170, 160, 77, 23);

        jButton8.setText("แปลงเป็น");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(170, 250, 77, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\budsaba\\budsaba\\ภาพ\\1.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 460, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 String input = b2.getText();
        Double a = Double.parseDouble(input);

        Double b = (a + 32) * 9 / 5;

        String output = String.format("%.3f", b);
        n2.setText(output);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void องศาฟาเรนไฮต์ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_องศาฟาเรนไฮต์ActionPerformed
String input = b1.getText();
        Double a = Double.parseDouble(input);

        Double b = (a - 32) * 5 / 9;

        String output = String.format("%.3f", b);
        n1.setText(output);        // TODO add your handling code here:
    }//GEN-LAST:event_องศาฟาเรนไฮต์ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 String input = b6.getText();
        Double a = Double.parseDouble(input);

        Double b = (a + 273.15);

        String output = String.format("%.3f", b);
        n6.setText(output);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
String input = b3.getText();
        Double a = Double.parseDouble(input);

        Double b = (a - 273.15);

        String output = String.format("%.3f", b);
        n3.setText(output);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
 String input = b4.getText();
        Double a = Double.parseDouble(input);

        Double b = (a * 1.25);

        String output = String.format("%.3f", b);
        n4.setText(output);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
 String input = b7.getText();
        Double a = Double.parseDouble(input);

        Double b = (a * 1.8) - 459.67;

        String output = String.format("%.3f", b);
        n7.setText(output);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
 String input = b5.getText();
        Double a = Double.parseDouble(input);

        Double b = (a * 0.8);

        String output = String.format("%.3f", b);
        n5.setText(output);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
 String input = b8.getText();
        Double a = Double.parseDouble(input);

        Double b = (a + 459.67) / 1.8;

        String output = String.format("%.3f", b);
        n8.setText(output);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ben2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ben2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ben2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ben2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ben2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField b1;
    private javax.swing.JTextField b2;
    private javax.swing.JTextField b3;
    private javax.swing.JTextField b4;
    private javax.swing.JTextField b5;
    private javax.swing.JTextField b6;
    private javax.swing.JTextField b7;
    private javax.swing.JTextField b8;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField n1;
    private javax.swing.JTextField n2;
    private javax.swing.JTextField n3;
    private javax.swing.JTextField n4;
    private javax.swing.JTextField n5;
    private javax.swing.JTextField n6;
    private javax.swing.JTextField n7;
    private javax.swing.JTextField n8;
    private javax.swing.JButton องศาฟาเรนไฮต์;
    // End of variables declaration//GEN-END:variables
}
