/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grade.pkg1;

import javax.swing.JOptionPane;

/**
 *
 * @author WITTAWATSK
 */
public class GPA extends javax.swing.JFrame {

    /**
     * Creates new form GPA
     */
    public GPA() {
        initComponents();
        setSize(930, 500);
        setLocation(250,100);
        getContentPane().setLayout(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        R7 = new javax.swing.JLabel();
        R1 = new javax.swing.JTextField();
        R6 = new javax.swing.JTextField();
        R3 = new javax.swing.JTextField();
        R4 = new javax.swing.JTextField();
        R5 = new javax.swing.JTextField();
        R2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jButton2.setBackground(new java.awt.Color(0, 102, 255));
        jButton2.setFont(new java.awt.Font("Ekkamai Standard", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("เริ่มใหม่");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(630, 210, 180, 70);

        jButton3.setBackground(new java.awt.Color(0, 102, 255));
        jButton3.setFont(new java.awt.Font("Ekkamai Standard", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("ออกจากระบบ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(630, 310, 180, 70);

        R7.setFont(new java.awt.Font("PGVIM", 1, 36)); // NOI18N
        R7.setForeground(new java.awt.Color(255, 255, 255));
        R7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(R7);
        R7.setBounds(760, 130, 80, 40);

        R1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        R1.setForeground(new java.awt.Color(0, 204, 204));
        R1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(R1);
        R1.setBounds(360, 190, 80, 30);

        R6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        R6.setForeground(new java.awt.Color(0, 204, 204));
        R6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(R6);
        R6.setBounds(360, 240, 80, 30);

        R3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(R3);
        R3.setBounds(360, 290, 80, 30);

        R4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(R4);
        R4.setBounds(360, 340, 80, 30);

        R5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(R5);
        R5.setBounds(360, 380, 80, 30);

        R2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(R2);
        R2.setBounds(360, 420, 80, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IM/คำนวณ.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(590, 60, 300, 130);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IM/cancel .png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(900, 0, 30, 30);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IM/down-arrow .png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4);
        jLabel4.setBounds(870, 0, 30, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IM/โปรแกรมGPA.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 930, 500);

        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(690, 30, 160, 40);

        jButton1.setText("jButton1");
        getContentPane().add(jButton1);
        jButton1.setBounds(610, 30, 73, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        this.setState(grade.pkg1.Login.ICONIFIED);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked

        try {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int result = JOptionPane.showConfirmDialog(null, "คุณต้องการออกจากโปรแกรมหรือไม่?","คุณกำลังจะออกจากโปรแกรม",dialogButton);
            if(result == 0){
                System.exit(0);
            }
        } catch (Exception e){
        }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
       Double eng,vik,pro,data,ase,sat,caleng,calvik,calpro,caldata,calase,calsat;
        String E,V,P,D,A,S, area;
        E = R1.getText();
        V = R2.getText();
        P = R3.getText();
        D = R4.getText();
        A = R5.getText();
        S = R6.getText();
        eng = Double.parseDouble(E);
        vik = Double.parseDouble(V);
        pro = Double.parseDouble(P);
        data = Double.parseDouble(D);
        ase = Double.parseDouble(A);
        sat = Double.parseDouble(S);
        caleng = 3 * eng;
        calvik = 3 * vik;
        calpro = 3 * pro;
        caldata = 3 * data;
        calase = 3 * ase;
        calsat= 3 * sat;
        area = String.valueOf ((caleng+calvik+calpro+caldata+calase+calsat)/18);
        R7.setText(area);       
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        R1.setText("");
        R2.setText("");
        R3.setText("");
        R4.setText("");
        R5.setText("");
        R6.setText("");
        R7.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
   Login second = new Login ();
        second.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GPA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GPA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GPA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GPA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GPA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField R1;
    private javax.swing.JTextField R2;
    private javax.swing.JTextField R3;
    private javax.swing.JTextField R4;
    private javax.swing.JTextField R5;
    private javax.swing.JTextField R6;
    private javax.swing.JLabel R7;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
